version: 1
formatters:
    simpleConsole:
        format: '%(module)s %(name)s %(levelname)s %(message)s'
    jsonFile:
        (): jsonLogging.CustomJsonFormatter
        format: '%(timestamp)s %(module)s %(name)s %(levelname)s %(message)s'

handlers:
    console:
        class:  logging.StreamHandler 
        level: INFO
        formatter: simpleConsole 
        stream: ext://sys.stdout 

    jsonFile:
        class: logging.FileHandler 
        level: DEBUG
        formatter: jsonFile 
        filename: jsonLogs.log 
        encoding: utf8


root:
    level: DEBUG 
    handlers: [console, jsonFile]


